---
apiVersion: v1
kind: Pod
metadata:
  name: utils
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  - name: sampleconfig
    persistentVolumeClaim:
      claimName: sampleconfig-pvc
  containers:
  - name: cryptogen
    image: hyperledger/fabric-tools:1.2.0
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /sampleconfig
      name: sampleconfig
