{{- if not .Values.persistence.storageClass }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared
{{- if .Values.persistence.storageClass }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.persistence.storageClass }}"
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
